name: Deploy NovaBlog Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Testar Servidor NovaBlog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependências (node_modules)
        run: npm install

      - name: Iniciar testes ou build
        run: npm run build --if-present
